name: Simple Build

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build-prod

      - name: Copy
        run: |
          cp -r ./public/graphics ./public/bundle
          cp -r ./public/index.html ./public/bundle


      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./public/bundle

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: 95.163.180.8
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ubuntu/frontend"
          strip_components: 1